# Generated by Django 5.1.6 on 2025-03-13 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_comment_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='content',
        ),
    ]
